language: node_js
node_js:
  - "5.6"
before_script:
  - npm install -g typings gulp webpack
  # `npm install` is run automatically
  - typings install
script:
  - gulp compile:web
notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#hearthsim"
    use_notice: true
    skip_join: true
    on_failure: always
    on_success: change
    template:
      - "(%{branch} @ %{commit} : %{author}): %{message} %{build_url}"
