language: node_js
node_js:
  - 8
  - 7
  - 6
env: NODE_ENV=dev
cache:
  - yarn
  - pip

jobs:
  include:
    - stage: deploy
      if: branch = master AND type = push
      node_js: 8
      env: NODE_ENV=production
      install:
        - npm install -g gulp webpack yarn
        - yarn --pure-lockfile
        - pip install --user awscli
      script:
        - yarn build
        - aws s3 sync --delete dist/ s3://$S3_DEFAULT_BUCKET/branches/$TRAVIS_BRANCH/
        - gulp sentry:release

install:
  - npm install -g gulp webpack yarn
  - yarn --pure-lockfile

script:
  - yarn build
  - yarn test

notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#hearthsim-commits"
    use_notice: true
    skip_join: true
    on_failure: always
    on_success: change
    template:
      - "(%{branch} @ %{commit} : %{author}): %{message} %{build_url}"
